### ISSUE TITLE
Cannot connect WiFi

### ISSUE THREAD

**Issue by benplace** [jsalin/esp8266_modem#1]
I know I am typing everything in correctly.  Is there a way to list available SSIDs?

**Comment by BloodStoneBBS** [comment]
IIRC, the ESP8266 requires ASCII for the SSID & password where your terminal may be sending PETSCII if C= or ATASCII if Atari etc...  Try a different terminal program to set the SSID & password.

**Comment by benplace** [comment]
I tried CCGMS and Z Term, both set to Ascii, the name of my Wifi is
CamaroGuy
Is there a character limit?  This is my wifi setting:

[image: Inline image 1]

**Comment by BloodStoneBBS** [comment]
No image but depending on which version modem you're using, you may need to ATC1 a few times.   As long as you are entering the information in ASCII, it should work. 
All of mine work fine with WPA2 once the SSID and password are entered but I still have to ATC1 from time to time on first access.  BTW, when I do, I see that the case is inverted on the connect and yes, it seems that the SSID is case sensitive.

**Comment by benplace** [comment]
This is what I am seeing:
https://www.youtube.com/watch?v=AmAT-2qrtyY

**Comment by BloodStoneBBS** [comment]
I must have lost a post...
That modem looks like one of Jason's. (Melbourne)  I have one too and had the same problem but again, after playing around with the case using ZTerm, I was able to get mine connected. I think the SSID was all upper and the pass was all lower. If your password is a mix, you may need to try several variations of case.

**Comment by benplace** [comment]
My SSID is a mix of upper/lower and my password is all lower case.
Should I try changing my SSID to be all upper case?

**Comment by benplace** [comment]
I tried making it BENGIG still didnt work

**Comment by BloodStoneBBS** [comment]
Best to start fresh...   AT&F, set your speed, set ssid and password AT&W and then try ATC1
Then if that doesn't work, play with case on the SSID and password but be sure to save between each attempt.  If no luck, best to reach out to Jason.

**Comment by benplace** [comment]
Tried all of that.  Is there a way to scan for available WiFi networks with
your program/firmware?

**Comment by BloodStoneBBS** [comment]
I'n not JSalin - just someone who watches this repo.

I just went out into the garage and loaded up the same modem.. IN CCGMS, my SSID was case inverted 
Switched to ASCII (F8) and hit ATC1, case was correct.  So, maybe load up CCGMS, hit F8, verify ASCII mode, clear the config AT&F, set baud rate, set SSID as set in the AP, set your password, write the config AT&W and try again. Maybe even shut down and reboot. Bring up CCGMS, hit enter to init the modem. May or may not connect on the first try. If not, hit ATC1. If still nothing, check your AP config. Maybe you have MAC filtering?

**Comment by BloodStoneBBS** [comment]
Documentation suggests AT+CLAP to show AP's
https://www.espressif.com/sites/default/files/documentation/4a-esp8266_at_instruction_set_en.pdf

**Comment by benplace** [comment]
None of those commands seem to work, I just tried a simple restart.  I type
at+rst and it returned error.  Is there some other format to enter these
commands?
So I tried all uppercase and same thing, error.
How do I enter a underscore?
Also tried reversing case on ssid, still wont connect.  I dont see an
option either for ASCII in CCGMS when I hit F8 I see Anscii and C/G as
options.

**Comment by benplace** [comment]
and I appreciate you taking the time to help me!

**Comment by BloodStoneBBS** [comment]
No prob.. The command to reset is AT&F not sure if ATZ works on these.  Hope you get it working!

**Comment by ksalin** [comment]
You can use space in the ssid, also underscore is Ok. For example: ATWIFIMy_WiFi,key
or: ATWIFIMy WiFi,key
Quoting and escaping is not supported. I think that comma is the only character that you can't have in SSID with the current implementation of parsing ATWIFI command, because it's used to mark the end of SSID and the beginning of the key.
Generally I don't recommend using weird letters like ' because for example it caused problems in some Linux WPA implementations.
I just tested and was able to connect to my Android phone's hot spot which had a space in the ssid.
Also note that this is just my implementation of just some AT commands, other people might have different commands in their esp8266 based virtual modem codes.

Also a good point about the upper and lower case inversion. Commodore petscii character set seems to have them inverted from ascii. This code simply passes the characters to esp8266 api, which expects ascii, so if you use petscii instead of ascii, you should reverse the case manually. There is no way for the code to know which character set is used for ssid, because the code is general purpose that can be also used by old PC and Amiga for example. It would be possible to add a AT command for that purpose in the future, which would enable a translation table, but it's easier to just manually reverse the case when typing the command. Also some special characters like _ might be of different value. I personally didn't even think about this because I used a terminal program that supports ascii, so it was the C64 doing the translation between character sets.

There is no command to scan and list SSID's. All available commands are in the source code and the welcome text. It might be possible to add such a command in the future if the api has that list available. I simply knew the ssid of my AP because I had set it up myself.
